# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='log_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.login'),
        ),
    ]
